name: update-lockfile

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 15 * *"

env:
  TF_INPUT: false
  TF_IN_AUTOMATION: true

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_TOKEN }}
      - uses: hashicorp/setup-terraform@v2.0.3 # https://github.com/hashicorp/setup-terraform/releases
        with:
          terraform_version: 1.5.5 # https://github.com/hashicorp/terraform/releases
          terraform_wrapper: false
      - uses: champ-oss/update-terraform-lockfile@v1.0.31-7cac677
        with:
          working-directory: examples/complete
          token: ${{ secrets.ACTION_TOKEN }}